apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.routerName }}
    router: {{ .Values.routerName }}
  name: {{ .Values.routerName }}
  namespace: {{ .Values.namespace }}
spec:
  externalTrafficPolicy: Local
  healthCheckNodePort: 30611
  ports:
  - name: http
    nodePort: 30939
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 31109
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: {{ .Values.routerName }}
  sessionAffinity: None
  type: LoadBalancer
